#Deploy do Postgres
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1
          env:
            - name: POSTGRES_PASSWORD
              value: label
            - name: POSTGRES_USER
              value: label              
            - name: POSTGRES_DB
              value: reviewfilmes
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
---  
#Deploy da aplicação
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: reviewfilmes
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
        - name: reviewfilmes
          image: gabrielgmm/reviewfilmes:v7
          env:
            - name: ASPENTCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Database=reviewfilmes;Username=label;Password=label"              
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 30000
  type: LoadBalancer




