name: CI-CD
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo fonte 1
        uses: actions/checkout@v4.1.7
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Faz o build da imagem e da o push para o docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            gabrielgmm/reviewfilmes:v${{github.run_number}}
            gabrielgmm/reviewfilmes:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 1
        run: "echo Deploy da aplicacao"
          
