name: CI-CD
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo fonte 1
        uses: actions/checkout@v4.1.7
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Faz o build da imagem e da o push para o docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            gabrielgmm/reviewfilmes:v${{github.run_number}}
            gabrielgmm/reviewfilmes:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do codigo fonte 2
        uses: actions/checkout@v4.1.7
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name:  Configuracao de contexto da aws
        run: "aws eks update-kubeconfig --name awscluster2"          
      - name: Deploy no Kubernet
        uses: Azure/k8s-deploy@v4.9
        with:
           manifests: |
              ./aws/deployment.yaml
           images: gabrielgmm/reviewfilmes:v${{github.run_number}}
           
        
          
